// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSG4oQxu9dAqoCOlQi-FlcxCZ86k7jdW4',
    appId: '1:333863448419:web:23d8f09d9be61688cf2d56',
    messagingSenderId: '333863448419',
    projectId: 'tugas-dhani',
    authDomain: 'tugas-dhani.firebaseapp.com',
    databaseURL: 'https://tugas-dhani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-dhani.appspot.com',
    measurementId: 'G-RJ46W81T5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgi2beALmt_63Yr2BEe1aOy_lDnofz8d8',
    appId: '1:333863448419:android:eb1bf141bce06c8acf2d56',
    messagingSenderId: '333863448419',
    projectId: 'tugas-dhani',
    databaseURL: 'https://tugas-dhani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-dhani.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1LOUyC8dMJVs80qRhXDoPAQu5GU3KsU8',
    appId: '1:333863448419:ios:cef51827e7f5f4f2cf2d56',
    messagingSenderId: '333863448419',
    projectId: 'tugas-dhani',
    databaseURL: 'https://tugas-dhani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-dhani.appspot.com',
    iosBundleId: 'com.example.tugasDhani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1LOUyC8dMJVs80qRhXDoPAQu5GU3KsU8',
    appId: '1:333863448419:ios:cef51827e7f5f4f2cf2d56',
    messagingSenderId: '333863448419',
    projectId: 'tugas-dhani',
    databaseURL: 'https://tugas-dhani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-dhani.appspot.com',
    iosBundleId: 'com.example.tugasDhani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSG4oQxu9dAqoCOlQi-FlcxCZ86k7jdW4',
    appId: '1:333863448419:web:1da14415f261b4aecf2d56',
    messagingSenderId: '333863448419',
    projectId: 'tugas-dhani',
    authDomain: 'tugas-dhani.firebaseapp.com',
    databaseURL: 'https://tugas-dhani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-dhani.appspot.com',
    measurementId: 'G-08PYS4JB7Y',
  );
}
